### ISSUE TITLE
%(RelativeDir) not working with Shared Projects in Visual Studio 2015?

### ISSUE THREAD

**Issue by FunnerSoft** [Microsoft/VisualStudio-SharedProject#22]
Hi there,

I am not sure if this is the best place to post this issue; hopefully it is ok.

I am getting errors like the following:

2>C:\Program Files             (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(838,5): error MSB3191: Unable to create directory "D:\SnapGames\Work\PC\SnapEdit\SnapEditEXE\Debug\D:\SnapGames\Work\PC\SnapEdit\SnapEdit\SnapEditCore\..\..\..\SnapCore\SnapCore\Code\Collision". The given path's format is not supported.

My Object File Name is set to "$(IntDir)%(RelativeDir)/". My IntDir is properly being set as "D:\SnapGames\Work\PC\SnapEdit\SnapEditEXE\Debug\", however the RelativeDir is incorrectly returning a full path.

I found and read the following:

https://github.com/Microsoft/TypeScript/issues/5894
http://stackoverflow.com/questions/34048228/tfs-build-error-after-installing-visual-studio-2015-update-1
http://stackoverflow.com/questions/34100740/error-copying-typescript-files-when-packaging-azure-project-visual-studio-2015

I have installed the TypeScript 1.7.6 referred to in the posts, but that didn't solve anything.

I have other solutions that are not using Visual Studio 2015 Shared Projects, and they are getting proper results from $(IntDir)%(RelativeDir)/. Therefore, I suspect this is related to using a Shared Project. However, I have not been able to find anything on this matter.

I took a 2015 solution that was building correctly. It has the same format of Outupt File Names that I described above. I re-implemented one of it's projects as a Shared Project, and it now fails with the same type of errors.

Any help would be appreciated

**Comment by zooba** [comment]
Looking at those issues, this seems to be unrelated to this project.

This repository is the project system used by PTVS, NTVS and a few other Visual Studio extensions, but not TypeScript or C++, so posting here won't help. I think you'd be better to start with the MSDN forums.

**Comment by FunnerSoft** [comment]
Oops. Thanks for the suggestion.
