### ISSUE TITLE
Visual Studio 2015 Slow Performace

### ISSUE THREAD

**Issue by som-nitjsr** [Microsoft/VisualStudio-SharedProject#25]
I am using VS 2015 on Windows 10 enterprise and it is very slow around 7-8 seconds.
when I am at my home it works perfecrtly(only connected to Git project). 
when I am in office it become two slow.
Note: I am connected to GitHub and TFS in team explorer.

I have not faced this issue with same setup/scenario on windows 7.

**Comment by zooba** [comment]
I'd suggest sending this feedback using the feedback tool within VS. This page is for the project system common to Node.js Tools and Python Tools, which it doesn't sound like you are using.
